name: Android Build and SonarCloud Analysis

on:
    workflow_dispatch:

    push:
        branches: [ main ]
        paths-ignore:
          - '**.md'
          - '.github/**'

    pull_request:
        branches: [ main ]
        types: [opened, synchronize, reopened]
        paths-ignore:
          - '**.md'
          - '.github/**'

jobs:

  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis [18]

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: write permissions to gradlew wrapper
      run: chmod +x gradlew

    - name: Run Unit Tests
      run: ./gradlew test
  
  emulator_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29,30,31,33,34]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3
        
    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}

    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew connectedCheck
  
  sonarcloud_scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis [18]

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: write permissions to gradlew wrapper
      run: chmod +x gradlew

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
#   - name: SonarCloud Scan
#      uses: SonarSource/sonarqube-scan-action@v4
#      env:
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        SONAR_HOST_URL: https://sonarcloud.io
  
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: app/src
        args: >
            -Dsonar.organization=javiercaparo
            -Dsonar.projectKey=javiercaparo_android-sonarcloud-test
            -Dsonar.verbose=true
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
  build_apk:
    runs-on: ubuntu-latest
    needs: [unit_tests, emulator_tests, sonarcloud_scan]
    timeout-minutes: 60
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: write permissions to gradlew wrapper
      run: chmod +x gradlew
    
    - name: Build apk
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 1